--My Coco puffs    
--My Coco puffs    
--My Coco puffs    
--My Coco puffs    
--My Coco puffs    
--My Coco puffs    
--My Coco puffs    
--My Coco puffs    
--My Coco puffs    
--My Coco puffs    
--My Coco puffs    
--My Coco puffs    
--My Coco puffs    
--My Coco puffs    
--My Coco puffs    
--My Coco puffs    
--My Coco puffs    
--My Coco puffs    
--My Coco puffs    
--My Coco puffs    
--My Coco puffs    
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--My Coco puffs    
--My Coco puffs    
--My Coco puffs    
--My Coco puffs    
--My Coco puffs    
--My Coco puffs    
--My Coco puffs    
--My Coco puffs    
--My Coco puffs    
--My Coco puffs    
--My Coco puffs    
--My Coco puffs    
--My Coco puffs    
--My Coco puffs    
--My Coco puffs    
--My Coco puffs    
--My Coco puffs    
--My Coco puffs    
--My Coco puffs    
--My Coco puffs    
--My Coco puffs    
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--My Coco puffs    
--My Coco puffs    
--My Coco puffs    
--My Coco puffs    
--My Coco puffs    
--My Coco puffs    
--My Coco puffs    
--My Coco puffs    
--My Coco puffs    
--My Coco puffs    
--My Coco puffs    
--My Coco puffs    
--My Coco puffs    
--My Coco puffs    
--My Coco puffs    
--My Coco puffs    
--My Coco puffs    
--My Coco puffs    
--My Coco puffs    
--My Coco puffs    
--My Coco puffs    
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
--Niahnihnahinahah
if game.PlaceId == 7419509075 then
    loadstring(game:HttpGet("https://raw.githubusercontent.com/hellamane/epixcryan/main/C.lua"))()
    else
        if game.PlaceId == 7047488135 then
            loadstring(game:HttpGet("https://raw.githubusercontent.com/hellamane/epixcryan/main/S.lua"))()
        else
        if game.PlaceId == 102131021 then
            loadstring(game:HttpGet("https://raw.githubusercontent.com/hellamane/epixcryan/main/F.lua"))()
            end
        end
    end
